### ISSUE TITLE
AWSless instructions for development

### ISSUE THREAD

**Issue by lagleki** [TiE23/metric-teacher#366]
It's be nice to have installation instructions for ubuntu/debian, without docker and traffik.

**Comment by TiE23** [comment]
For prod and dev you will still need Docker in order to run the [PrismaDB](https://hub.docker.com/r/prismagraphql/prisma/) + MySQL stack. The only alternative to Docker is to either figure out how to do it all manually yourself (I can't help you there, sorry, I'd recommend looking at Prisma's [docs](https://www.prisma.io/docs), [forums](https://www.prisma.io/forum/), or [slack](https://prisma.slack.com/)) or to use [Prisma's Cloud service](https://www.prisma.io/cloud), which I've avoided, preferring to spin up my own local Docker instances for development and use Docker-Machines on AWS for production. 

Concerning the PrismaDB + MySQL stack, follow the steps in the [dotEnv section](https://github.com/TiE23/metric-teacher/tree/master/server#dotenv) to learn how to configure the secrets and other essential values in `./server/.env` and `~/.prisma/config.yml`.

Traefik is easily optional (in fact, it's much harder with) in that you would run `docker-compose-aws-prod.yml` instead of `docker-compose-aws-prod-traefik.yml` when going to prod. Comments in each file (one for database, one for server, one for client) with `-traefik` in the name describe what extra data on your host machines are necessary.

----

Running the client and server locally for development is simple, there are NPM scripts already in place. 

For **client** you execute `npm run start`, where it'll build the CSS and run a dev version (not prod build) and use create-react-app's standard set-up to make development easy. To skip the CSS build process and save a lot of time just run `npm run fast-start`.

For **server** you just execute `npm run start`, it'll just start running immediately (and have debug output) with nodemon executing it so that changes are reflected on save.

----

So, to run Metric-Teacher's client and server on AWS without docker would require you to pull the code to that remote machine, have node and npm installed, install all the modules for both.

Build **client** with `npm run build` and then host it with `serve --single --listen=80 ./build`. You can set the port with the listen argument, obviously.

Run **server** with `PRISMA_DEBUG="false" npm run start`. You can set the port with env var `PORT`, as well. (Setting the env var `PRISMA_DEBUG` to "false" will disable debug output, which prints out all responses, which includes plain text passwords, so don't log it if you respect privacy)

----

If you need help debugging client or server with WebStorm locally just let me know and I'll share my Run/Debug Configurations with you.

**Comment by lagleki** [comment]
Looks like the client fails to install under Node v.12

`gulp build` leads to

```
fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
```
caused by Gulp v.3
However, upgrading to Gulp v.4 doesn't help either. semantic-ui supports Gulp v.3 only.

Replacing semantic-ui with its fork fomantic-ui +  upgrading gulpfile.js could be a solution.

**Comment by TiE23** [comment]
I would think that trying to swap out semantic-ui with a fork would probably be a larger cause of issues relating to the [semantic-ui-react](https://github.com/Semantic-Org/Semantic-UI-React) package Metric-Teacher.

I'd suggest just simply sticking to LTS Node v10 that I used to develop the website in. When semantic-ui updates to use Gulp v4 then an upgrade of Node could be considered.

Use [nvm](https://github.com/nvm-sh/nvm/blob/master/README.md) if you need help keeping Node versions straight - it's really not half-bad!
