### ISSUE TITLE
As a tool to learn spoken languages?

### ISSUE THREAD

**Issue by lagleki** [TiE23/metric-teacher#367]
Metric Teacher in its current form is pretty impressive. Do you have any ideas how it can be improved to become a tool to learn spoken languages? 
One thing I have in mind is to add audio (uploadable via admin interface) for each question. 
Another one is to have reshuffled words that you need to order to get a correct translation.
Anything else?

**Comment by TiE23** [comment]
Uh. Well, that'd be quite a jump, but I don't see the point.

I was inspired by [Duolingo](https://www.duolingo.com/
), a very mature and well known language teaching app that is magnitudes more complex and intelligent than my project. Heck, I'd consider applying for a job with them if their jobs weren't primarily in Pittsburgh and not Seattle. They have well over 100 employees.

I have no plans to go beyond the metric system. More subjects and units? Sure. Implement classroom and teacher systems? Yeah, I have API endpoints supporting them. Pre-made challenges? Definitely possible. Greatly improve progress tracking and challenge generation? That'd be great.

But to be honest I don't really expect to be adding much more to this project - at least for the foreseeable future. I do hope to try advertising this website publicly, aggressively, once I've found a job. Metric-Teacher was a personal project to teach myself to be a full-stack JS developer so I could get a job as one. I'm wary about having the great fortune of hundreds of visitors at once (I dream about someone like Bill Nye, NDT, Veritasium, VSauce, or any other pop-sci celeb tweeting a link to Metric-Teacher) as they could break the site, greatly harming my ability to show this site off as a star portfolio item to potential employers. It'd kill me if I said "here's my website!" and it's completely shut down. D:

Otherwise, I just place this site's code and entire repo publicly as a demo for other software engineers who are also new to React + Node + GraphQL projects. 

There are aspects to Metrification that I wish I had learned about before I began my project. If you're interested in the subject I'd recommend looking at The Metric Maven's website, especially starting with his section on [Naughtin's Laws](http://themetricmaven.com/?page_id=558). It's really quite interesting.

Also, there is [AnkiApp](https://www.ankiapp.com/) for generalized flashcard techniques if you were wondering about it. Never really used it myself, but there are lots of flashcard libraries you can find online for hundreds of different subjects.
